version: '3.4'

services: 
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=stronger_password
      - MONGO_INITDB_DATABASE=hotelReservaties 
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: stronger_password
      ME_CONFIG_MONGODB_URL: mongodb://root:stronger_password@mongodb:27017/

  mariadb:
    image: mariadb:10.5.9
    env_file:
      - ./Back-End/ormconfig.json
      - ./Back-End/.env
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql

  adminer:
    image: adminer:4.8.1
    ports:
      - 9999:8080

  backend: 
    image: ghcr.io/vanhouttetibo/advfs-hotelreservaties-backend:2.0
    build: ./Back-End
    ports:
      - 3000:3000
    env_file:
      - ./Back-End/docker.firebase.env
    volumes:
      - ./Back-End/server/auth/srvc-account.json:/usr/app/auth/service-account.json
      - ./Back-End/docker.ormconfig.json:/usr/app/ormconfig.json
    depends_on:
      - mongodb
      - mariadb
    labels:
      kompose.service.type: nodeport

  frontend: # name of the first service
    image: ghcr.io/vanhouttetibo/advfs-hotelreservaties-frontend:1.0
    build: Front-End/HotelReservaties # specify the directory of the Dockerfile
    ports:
      - 4200:80 # specify port forewarding  
    depends_on:
      - backend
    labels:
      kompose.service.type: nodeport
  socketio: # name of the first service
    image: ghcr.io/vanhouttetibo/advfs-hotelreservaties-socketio:2.0
    build: HotelSocketio # specify the directory of the Dockerfile
    ports:
      - 3010:3010 # specify port forewarding   
    depends_on:
      - frontend
      - backend
    labels:
      kompose.service.type: nodeport

volumes:
  mongodb:
  database:
